Repository michelecomfort/fitlit, pull requests merged in 2021-11, with the labels that each got.

#66 Feature/activity class
  src/Activity.js
  src/data/sampleData.js
  test/Activity-test.js
Labels: feature

#67 Feature/user repo
  README.md
  dist/index.html
  src/DataManager.js
  src/UserRepository.js
  src/css/styles.css
  src/sampleData.js
  src/scripts.js
  test/UserRepository-test.js
Labels: enhancement

#71 Feature/dom manipulation
  dist/index.html
  src/charts.js
  src/css/styles.css
  src/domManipulation.js
  src/scripts.js
Labels: enhancement, feature, refactor

#70 Complete additional activity methods, refactor to be more dynamic
  src/Activity.js
  src/UserRepository.js
  test/Activity-test.js
Labels: enhancement

#72 Feature/charts
  src/Activity.js
  src/User.js
  src/charts.js
  src/scripts.js
Labels: enhancement

#73 Feature/dom functionality
  dist/index.html
  src/charts.js
  src/domManipulation.js
  src/scripts.js
Labels: enhancement, ui/ux

#74 Feature/user input form
  dist/index.html
  src/UserRepository.js
  src/css/styles.css
  src/scripts.js
Labels: feature

#77 Refactor/sassy css
  src/css/mixin.scss
  src/css/reset.scss
  src/css/styles.scss
  src/css/variables.scss
  src/scripts.js
  webpack.config.js
Labels: ui/ux

#82 Begin CSS refactor, adjust today activity method for DOM
  dist/index.html
  src/Activity.js
  src/css/mixin.scss
  src/css/styles.scss
  src/domManipulation.js
  src/scripts.js
Labels: refactor

#89 Refactor/html css
  dist/index.html
  src/css/mixin.scss
  src/css/styles.scss
  src/domManipulation.js
  src/scripts.js
Labels: refactor

#90 Final CSS refactor
  src/css/styles.scss
  src/domManipulation.js
Labels: refactor

#92 Repass all tests
  src/Activity.js
  test/Activity-test.js
  test/Hydration-test.js
  test/Sleep-test.js
  test/User-test.js
Labels: refactor

#97 Debug script.js query selector
  src/scripts.js
Labels: bug
